# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, choices=[('F', 'Family'), ('W', 'Work'), ('P', 'Personal')], default='W', max_length=1)),
                ('priority', models.CharField(blank=True, choices=[('H', 'High'), ('N', 'Normal'), ('L', 'Low')], default='N', max_length=1)),
                ('should_do_before', models.DateField(default=datetime.date.today)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
